Fix duplicate elements (sveltejs/sapper#1725)
sveltejs/sapper-template pull request #306
Opened 2021-03-17 20:34 UTC by babeard

2021-03-17 20:48 UTC, benmccann commented
thanks for tracking this down. I wonder if the better fix wouldn't be to wait to call `start` on load instead instead in https://github.com/sveltejs/sapper-template/blob/master/src/client.js

2021-03-17 21:02 UTC, benmccann commented on src/template.html
> +
can you revert the changes to this file? no need for the blank lines at the end and the comment no longer aligns

2021-03-17 21:03 UTC, benmccann commented on src/template.html
> +</html>
no need to remove the blank line at the end of the file

2021-03-17 21:03 UTC, benmccann approved these changes

2021-03-17 21:13 UTC, Conduitry commented
Huh. What exactly needs to wait for what - and what needs to be fixed - now that Sapper is using `<script defer>`? https://github.com/sveltejs/sapper/pull/1123

2021-03-17 21:58 UTC, babeard commented
Defer or not doesn't seem to affect the hydration/duplication problem unfortunately. I'm not sure why because spec says that deferred scripts are `fetched in parallel and evaluated when the page has finished parsing.` I'm not quite sure what else would be going on beside's Chrome not strictly adhering to spec. In Firefox, for example, this issue does not appear.

Why is the window load event preferred over moving scripts to the end of the body?  Just curious.

_Also, sorry for the poor "gitfu". I'm learning as I go. Any pointers are appreciated!_

2021-03-17 22:13 UTC, benmccann commented
> Why is the window load event preferred over moving scripts to the end of the body? Just curious.

The the script is encountered soon and can start being parsed sooner. Probably doesn't make much of a difference with the small document size, but it is better practice

2021-03-17 22:21 UTC, benmccann requested changes
I'm also questioning now whether the document not being loaded yet would result in the behavior being seen. If you try to create a Svelte app when the target element is present you get the message `'target' is a required option`, so it wouldn't end up creating them twice and I don't think it's the case that the script is being run before the target element is present unless I'm missing something

2021-03-18 01:50 UTC, babeard commented
> I'm also questioning now whether the document not being loaded yet would result in the behavior being seen.

My original hypothesis may be totally incorrect, but the two fixes below do resolve the issue we're seeing. Now the question is why.

#### Brief summary of observations
- Chrome based browsers only
- Initial SSR renders correctly, then duplicate elements appear (presumably on hydration)
- Issue appears when on slower network and in combination with a larger client-[hash].js (in [this case](https://github.com/bardobrado/sample_sapper), it's png files inlined via base64)
- Initial page load doesn't seem to be affected, only on subsequent refreshes.
- Disabling cache via chrome devtools eliminates the issue as well.
- Disabling service-worker does not fix.
- Occurs in all versions of Sapper down to and including 0.27.x. (I have not tested below that). I believe the reason that quite a few people are seeing this error migrating from 0.27 is because the [migration guide](https://sapper.svelte.dev/migrating#0_27_to_0_28) suggests `%sapper.scripts% can be moved to the <head> section for slightly better performance`.

#### Working Fixes
- append `%sapper.scripts%` to body
- start sapper client on load event (currently this PR)

2026-03-12 19:51 UTC, closed without merging